[workspace]
members = [
    "programs/*",
    # Drop everything below this line before running "anchor publish":
    # Otherwise the build will fail since Anchor uploads only parts of the source tree.
    "cli/"
]
